sudo: required

services:
- docker

before_install:
- docker-compose --version
- sudo rm -f /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version
install:
- docker-compose build
- docker-compose up -d
script:
- docker exec rldb-flask python test.py
- docker exec -e CI=true rldb-react npm test
after_success:
- if [ "$TRAVIS_BRANCH" == "docker-deploy-fixes" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push janabimustafa/rldb-flask;
  docker push janabimustafa/rldb-react;
  fi
