sudo: required

services:
- docker

before_install:
- docker-compose --version

install:
- docker-compose build
- docker-compose up -d
script:
- docker exec rldb-flask python test.py
- docker exec -e CI=true rldb-react npm test
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push janabimustafa/rldb-flask;
  docker push janabimustafa/rldb-react;
  fi
