sudo: required

services:
- docker

before_install:
- docker-compose --version

install:
- docker-compose build
- docker-compose up -d
script:
- docker exec rldb-flask python test.py
- docker exec -e CI=true rldb-react npm test
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then  
  docker push janabimustafa/rldb-flask;
  docker push janabimustafa/rldb-react;
  elif [ "$TRAVIS_BRANCH" == "dev" ]; then
  docker tag janabimustafa/rldb-flask janabimustafa/rldb-flask:dev;
  docker tag janabimustafa/rldb-react janabimustafa/rldb-react:dev;
  docker push janabimustafa/rldb-flask:dev;
  docker push janabimustafa/rldb-react:dev;
  fi
