debug = true
checkNewVersion = true
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[retry]

[file]
filename = "/servers.toml"
watch = true
